/** A single 2-minute atomic action within an atomized task. */
export interface AtomicStep {
  /** Unique identifier for this step. */
  id: string;
  /** Human-readable action description (≤2 min to complete). */
  text: string;
  /** Whether the user has marked this step done. */
  completed: boolean;
}

/** The full in-progress atomized task persisted across sessions. */
export interface AtomizerTask {
  /** The original "scary task" string entered by the user. */
  originalTask: string;
  /** Ordered list of atomic steps generated by AI. */
  steps: AtomicStep[];
  /** How many energy-check interrupts have fired (increments every 6 completions). */
  energyCheckCount: number;
  /** ISO 8601 datetime when the task was created. */
  createdAt: string;
}

/** localStorage key used to persist the active task across page loads. */
export const STORAGE_KEY = 'duckos:atomizer:active_task';

/**
 * Persists an atomized task to localStorage.
 * Pass `null` to clear the stored task (e.g. on completion or abandon).
 * No-ops safely in non-browser environments (SSR guard).
 *
 * @param task - The task to save, or `null` to remove.
 */
export function saveAtomizerTask(task: AtomizerTask | null): void {
  if (typeof window === 'undefined') return;
  if (!task) {
    localStorage.removeItem(STORAGE_KEY);
  } else {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(task));
  }
}

/**
 * Loads the active atomized task from localStorage.
 * Returns `null` if no task is stored or if called server-side.
 *
 * @returns The persisted `AtomizerTask`, or `null`.
 */
export function loadAtomizerTask(): AtomizerTask | null {
  if (typeof window === 'undefined') return null;
  const saved = localStorage.getItem(STORAGE_KEY);
  return saved ? (JSON.parse(saved) as AtomizerTask) : null;
}
